server:
  port: 8082

spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:springapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot!!

---

spring:
  profiles: qa
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:springapp
    username: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
welcome:
  message: Welcome to spring boot!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:springapp
    username: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
welcome:
  message: Welcome to spring boot!!
